# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
dist: bionic
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - python: 3.7.6
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py37" COVERAGE="true"
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "rockdreamer@gmail.com"
  - git config --global user.name "Claudio Bantaloukas"
script:
  - python setup.py develop
  - tox
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
